"""Initial schema baseline

Revision ID: e09949059341
Revises: 
Create Date: 2026-03-30 00:50:57.380786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09949059341'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_status'), ['status'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'), sqlite_where=sa.text('invoice_number IS NOT NULL'))
        batch_op.create_unique_constraint(None, ['invoice_number'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_date'), ['payment_date'], unique=False)

    with op.batch_alter_table('recurring_skips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_skips_recurring_stop_id'), ['recurring_stop_id'], unique=False)

    with op.batch_alter_table('recurring_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_stops_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_stops_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_route_stops_date_completed', ['route_date', 'completed'], unique=False)
        batch_op.create_index('ix_route_stops_date_customer', ['route_date', 'customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_stops_route_date'), ['route_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_stops_route_date'))
        batch_op.drop_index('ix_route_stops_date_customer')
        batch_op.drop_index('ix_route_stops_date_completed')
        batch_op.drop_index(batch_op.f('ix_route_stops_customer_id'))

    with op.batch_alter_table('recurring_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_stops_customer_id'))

    with op.batch_alter_table('recurring_skips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_skips_recurring_stop_id'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=1, sqlite_where=sa.text('invoice_number IS NOT NULL'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_status'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_city'))

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_customer_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    # ### end Alembic commands ###
